### ISSUE TITLE
[BUG反馈] 课程KeyError

### ISSUE THREAD

**Issue by QuantumLiu** [Samueli924/zhihuishu#5]
**形容Bug的信息**
课程2没问题，课程1会报错
┌──────┬──────────────┬────────┬───────────────────────┬──────────┬───────────────┬───────────────┬──────────┐
│ 序号 │ 课程名       │ 老师   │ 正在学习              │ 学习进度 │ 开始时间      │ 结束时间      │ 存在记录 │
├──────┼──────────────┼────────┼───────────────────────┼──────────┼───────────────┼───────────────┼──────────┤
│ 1    │ 大众传媒文化 │ 胡春阳 │ 1.1.2大众媒介案例介绍 │ 0%       │ 1633881600000 │ 1637942399000 │ 不存在   │
│ 2    │ 营销管理     │ 熊国钺 │ NoneNone              │ 0%       │ 1633881600000 │ 1637942399000 │ 不存在   │
└──────┴──────────────┴────────┴───────────────────────┴──────────┴───────────────┴───────────────┴──────────┘
请输入您要查询的课程序号1
[15:45:43] Cookies数据传递完毕                                                                               show.py:32
           开始读取课程信息:'大众传媒文化'                                                                   show.py:82
[15:45:43] 开始获取所有视频的详细信息                                                                        load.py:44
           开始处理获取得到的videolist                                                                       load.py:57
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    all_videos, lessons, finished = load.load_all(s,match['secret'],uuid,match['recruitid'],usernm)
  File "C:\pyprojects\zhihuishu\src\video\load.py", line 86, in load_all
    lessons, finished = load_studyinfo(s, recruit, uuid, big, small)
  File "C:\pyprojects\zhihuishu\src\video\load.py", line 29, in load_studyinfo
    for i in resp.json()['data']['lesson']:
KeyError: 'lesson'

**运行环境 (请完善以下信息):**
 - 系统：win10
 - Python环境版本:py36
 - 运行方式: 可以私信给你我的账号密码
 - 代码版本:git最新

**其他内容**
您觉得对问题反馈有帮助的内容

**Comment by Samueli924** [comment]
你好 如果可以的话麻烦提供一下账号密码吧 谢谢
csk@samuelchen.cn
